[project]
name = "MaskerLogger"
version = "0.0.1"
description = "A common logging module for all our tools."
authors = [
  { name = "Tamar Galer", email = "tamar@ox.security" },
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pyahocorasick = "^2.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
